import React, { useState } from 'react';
import { Sliders, Save, Check } from 'lucide-react';
import { gql, FALLBACK_RULES } from '../api.js';

export default function AdminPluginsTab({
  username,
  rules = FALLBACK_RULES,
  syncedSettings,
  onUpdateSyncedSettings,
  onToggleRule,
  onUnauthorized
}) {
  const [settingsSaved, setSettingsSaved] = useState(false);

  const handleSave = async () => {
    try {
      const res = await gql(`
        mutation SaveSettings {
          updateSyncedSettings(input: {
            userId: "${username}",
            serverUrl: "${syncedSettings.serverUrl}",
            serverUsername: "${syncedSettings.serverUsername}",
            lrclibUrl: "${syncedSettings.lrclibUrl}",
            lyricsFetchOnline: ${syncedSettings.lyricsFetchOnline},
            streamFormat: "${syncedSettings.streamFormat}",
            shareDomain: "${syncedSettings.shareDomain}",
            shareHosts: "${syncedSettings.shareHosts}",
            shareEnabled: ${syncedSettings.shareEnabled}
          }) {
            updatedAt
          }
        }
      `);
      if (res.ok) {
        setSettingsSaved(true);
        setTimeout(() => setSettingsSaved(false), 2000);
      }
    } catch (e) {
      if (e.unauthorized) onUnauthorized?.();
    }
  };

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '16px' }}>
      {/* Share link forwarding */}
      <div className="card">
        <div className="card-header">
          <div className="card-title">Smart Share Links Domain</div>
          <button
            className={`btn ${syncedSettings.shareEnabled ? 'btn-primary' : ''}`}
            onClick={() => onUpdateSyncedSettings({ ...syncedSettings, shareEnabled: !syncedSettings.shareEnabled })}
          >
            <span>{syncedSettings.shareEnabled ? 'Enabled' : 'Disabled'}</span>
          </button>
        </div>

        <p style={{ fontSize: '12px', color: 'var(--text-muted)', margin: '0 0 12px' }}>
          When enabled, share links generated by Wanda and Wander route through this domain.
        </p>

        <div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: '12px' }}>
          <div>
            <label className="form-label">Share Domain</label>
            <input
              type="text"
              placeholder="share.example.com"
              className="form-input"
              value={syncedSettings.shareDomain}
              onChange={(e) => onUpdateSyncedSettings({ ...syncedSettings, shareDomain: e.target.value })}
            />
          </div>
          <div>
            <label className="form-label">Forward To (comma separated)</label>
            <input
              type="text"
              placeholder="music.example.com"
              className="form-input"
              value={syncedSettings.shareHosts}
              onChange={(e) => onUpdateSyncedSettings({ ...syncedSettings, shareHosts: e.target.value })}
            />
          </div>
        </div>

        <div style={{ marginTop: '12px', textAlign: 'right' }}>
          <button className="btn btn-secondary" onClick={handleSave}>
            {settingsSaved ? <Check size={13} color="var(--status-active)" /> : <Save size={13} />}
            <span>{settingsSaved ? 'Saved!' : 'Save Domain Settings'}</span>
          </button>
        </div>
      </div>

      {/* Sync Rules */}
      <div className="card">
        <div className="card-header">
          <div className="card-title">Plugins & Core Sync Rules</div>
        </div>

        <div className="rules-list">
          {rules.map(rule => (
            <div key={rule.id} className={`rule-row ${!rule.isEnabled ? 'disabled' : ''}`}>
              <div className="rule-info">
                <div className="rule-title">
                  {rule.name}
                  <span className="rule-tag">{rule.target}</span>
                </div>
                <div className="rule-desc">{rule.description}</div>
              </div>

              <label className="switch">
                <input
                  type="checkbox"
                  checked={rule.isEnabled}
                  onChange={() => onToggleRule(rule.id)}
                />
                <span className="slider" />
              </label>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
}
